#!/usr/bin/env bash

# Resize everything in the folder to 256x256
# by Miguel Martinez Chapa
#
# NOTE: This will rename everything in the folder as:
#   folder_name-num_image
# This script also only expects .png images

USAGE="./resize_files folder"

if [ "$#" -ne 1 ]; then
  echo "Illegal number of parameters"
  echo "Usage:" $USAGE
fi

if [ ! -d "$1" ]; then
  echo "Error: directory $1 does not exist"
  exit
fi

# Get the base filename
BASENAME=$(basename $1)

i=1
for file in $1/*
do
  convert $file -resize 256x256 "$1/${BASENAME}-${i}.png"
  rm $file

  i=$(( $i + 1 ))
done

echo "All done!"
